// File generated by flutterfire_cli.
// Run `flutterfire configure --project=excelerate-app-4b169` to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhpUv4oili2S4jkEoR1YyQ_IbUBzxKqQ',
    appId: '1:37077923691:web:7a35d9f948286f74affe2e',
    messagingSenderId: '37077923691',
    projectId: 'excelerate-app-4b169',
    authDomain: 'excelerate-app-4b169.firebaseapp.com',
    storageBucket: 'excelerate-app-4b169.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVTBG5MkVwK9ZaZ9Z9Z9Z9Z9Z9Z9Z9Z9',
    appId: '1:123456789012:android:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'excelerate-app-4b169',
    storageBucket: 'excelerate-app-4b169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVTBG5MkVwK9ZaZ9Z9Z9Z9Z9Z9Z9Z9Z9',
    appId: '1:123456789012:ios:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'excelerate-app-4b169',
    storageBucket: 'excelerate-app-4b169.appspot.com',
    iosBundleId: 'com.excelerate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEVTBG5MkVwK9ZaZ9Z9Z9Z9Z9Z9Z9Z9Z9',
    appId: '1:123456789012:macos:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'excelerate-app-4b169',
    storageBucket: 'excelerate-app-4b169.appspot.com',
    iosBundleId: 'com.excelerate.app',
  );
}
